In [1]:
import torch
import math

In [2]:
thetas = torch.arange(
    8, dtype=torch.float32) * (2.0 * math.pi / 8)

In [3]:
thetas

tensor([0.0000, 0.7854, 1.5708, 2.3562, 3.1416, 3.9270, 4.7124, 5.4978])

In [4]:
grid_init = torch.stack([thetas.cos(), thetas.sin()], -1)

In [5]:
grid_init

tensor([[ 1.0000e+00,  0.0000e+00],
        [ 7.0711e-01,  7.0711e-01],
        [-4.3711e-08,  1.0000e+00],
        [-7.0711e-01,  7.0711e-01],
        [-1.0000e+00, -8.7423e-08],
        [-7.0711e-01, -7.0711e-01],
        [ 1.1925e-08, -1.0000e+00],
        [ 7.0711e-01, -7.0711e-01]])

In [21]:
grid_init1 = torch.cat([thetas.cos(), thetas.sin()])

In [22]:
grid_init1

tensor([ 1.0000e+00,  7.0711e-01, -4.3711e-08, -7.0711e-01, -1.0000e+00,
        -7.0711e-01,  1.1925e-08,  7.0711e-01,  0.0000e+00,  7.0711e-01,
         1.0000e+00,  7.0711e-01, -8.7423e-08, -7.0711e-01, -1.0000e+00,
        -7.0711e-01])

In [ ]:

value_list = value.split([H_ * W_ for H_, W_ in value_spatial_shapes],
                            dim=1)